<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class TransactionTest extends \ApiPlatform\Symfony\Bundle\Test\ApiTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testPagination(): void
    {
        $response = static::createClient()->request('GET', '/transaction');

        self::assertResponseIsSuccessful();
        self::assertJsonContains(['@id' => '/']);
    }
}
